//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovik.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressTo()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int IdAddressTo { get; set; }
        public int IdCityTo { get; set; }
        public int IdStreetTo { get; set; }
        public int House { get; set; }
        public Nullable<int> Flat { get; set; }
        public Nullable<int> Housing { get; set; }
    
        public virtual CityTo CityTo { get; set; }
        public virtual StreetTo StreetTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
