//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovik.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Personal = new HashSet<Personal>();
        }
    
        public int IdOrder { get; set; }
        public int IdAddress { get; set; }
        public int IdClient { get; set; }
        public int IdRestourant { get; set; }
        public int IdAddressTo { get; set; }
        public int IdMenu { get; set; }
    
        public virtual AddressTo AddressTo { get; set; }
        public virtual Client Client { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Restoraunt Restoraunt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal> Personal { get; set; }
    }
}
